### ISSUE TITLE
Steam APIs sometimes returning no data causing error

### ISSUE THREAD

**Issue by kt1996** [Tr345ure/xplay-store-enhance#2]
![image](https://github.com/Tr345ure/xplay-store-enhance/assets/15853215/2e0593b7-b257-41a6-94fd-a1e04ab6ef66)

Sometimes I was getting an error, on checking logs found that sell_price_text was undefined.

Further dumping the steam response in console noticed that 

![image](https://github.com/Tr345ure/xplay-store-enhance/assets/15853215/f3102172-776f-46f2-b7de-1364db992829)

the response's result array was itself of size 0.

----------------------------------------------------------------------------------------

Thinking a simple loop check with X (say 5) retries if steam sends data with results array length 0 would be a simple fix, as I noticed that steam sent invalid response max 2-3 times.

**Comment by Tr345ure** [comment]
Thanks for creating this issue. I've been aware of that problem for a while now, but since it was usually fixed with clicking the "Load Price" button again for a few times, there has been no fix for it yet.

Probably I also have to pay attention to rate limits if I want to implement re-tries.

I'm busy this weekend, but I'll work on a fix to improve QoL as soon as I can.

**Comment by Tr345ure** [comment]
Just pushed an update for this: a1c87156cf38f0fb12b873b6548b45f72c2a7cd0

If you manually modified your script, remember to re-add the update source in the script settings since TamperMonkey will disable automatic updates.
